import { borderStyles } from '../../commonStyles';

export default {
  root: {
    display: 'flex',
    marginTop: 50,
  },
  productInfo: {
    ...borderStyles,
    borderWidth: 1,
    display: 'flex',
    flex: 0.2,
    maxWidth: 270,
    flexDirection: 'column',
    borderRadius: 2.5,
    borderCollapse: 'collapse',
    backgroundColor: '#fff',
    marginLeft: 15,
    boxShadow: '11px 0px 22px -6px rgba(0,0,0,0.19)',
    height: '100%',
  },
  productTags: {
    display: 'flex',
    flexWrap: 'wrap',
    borderStyle: 'solid',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    borderColor: '#CDCDCD',
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 6,
    paddingBottom: 6,
  },
  productTag: {
    display: 'flex',
    ...borderStyles,
    borderWidth: 1,
    borderRadius: 3,
    textAlign: 'center',
    paddingLeft: 6,
    paddingRight: 6,
    marginTop: 4,
    marginBottom: 4,
    marginRight: 8,
    flexShrink: 0,
    fontSize: 14,
  },
  graphsAndCharts: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    marginLeft: 15,
    marginRight: 15,
  },
  productImage: {
    maxWidth: 130,
    paddingBottom: 20,
    alignSelf: 'center',
    paddingTop: 10,
  },
  title: {
    textAlign: 'center',
    fontWeight: 'bold',
    paddingBottom: 4,
    fontSize: 16,
  },
  subTitle: {
    color: '#AAA',
    fontSize: 12,
    textAlign: 'center',
    marginLeft: '15%',
    marginRight: '15%',
    paddingBottom: 14,
  },
  salesChart: {
    backgroundColor: '#fff',
  },
  dataTable: {
    marginTop: 40,
    backgroundColor: '#fff',
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    fontSize: 14,
    marginBottom: 12,
    paddingTop: 16,
    paddingLeft: 18,
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  icon: {
    marginRight: 12,
  },
};
